#!/usr/bin/env python3

from pathlib import Path

TARGET_DIR = Path("/usr/local/bin")

for executable in TARGET_DIR.glob("highlight*"):
    print(f"Removing symlink for {executable}")
    executable.unlink(missing_ok=True)
