name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      
      - name: Install packaging tool
        run: gem install fpm
      
      - name: Install build tools
        run: |
          pip3 install --upgrade pip setuptools build virtualenv virtualenv-tools3 toml-cli

      - name: Build Python .whl 
        run: python3 -m build

      - name: Build .deb Package
        run: >
          fpm
          --verbose
          --input-type=virtualenv
          --output-type=deb
          --name=$(toml get --toml-path pyproject.toml project.name)
          --prefix=/opt/$(toml get --toml-path pyproject.toml project.name)
          --version=$(toml get --toml-path pyproject.toml project.version)
          --after-install=after-install
          --after-remove=after-remove
          $(find ./dist/*.whl)

      - name: Test installing .deb
        run: sudo apt-get install -yqq "./$(basename *.deb)"
      
      - name: Test removing .deb
        run: sudo apt-get remove -yqq highlight      
      
      - name: Upload .deb Package
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: testing
          files: "*.deb"
