name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      
      - name: Install packaging tool
        run: gem install fpm
      
      - name: Install build tools
        run: |
          pip3 install --upgrade pip setuptools build virtualenv virtualenv-tools3
          # apt install python-is-python3

      - run: python3 --version
      - run: python --version
